# Generated by Django 4.2.7 on 2023-12-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_author_book_remove_product_company_delete_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
